// <auto-generated />
using ExaminaFinalVersion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExaminaFinalVersion_Wallahi.Migrations
{
    [DbContext(typeof(ContextClass))]
    [Migration("20210501212255_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExaminaFinalVersion.Models.Courses", b =>
                {
                    b.Property<int>("Course_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course_Image");

                    b.Property<string>("Course_Name");

                    b.Property<int>("Professor_ID");

                    b.HasKey("Course_ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.CourseStudentRelationship", b =>
                {
                    b.Property<int>("CourseStudentRelationshipID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID");

                    b.Property<int>("StudentID");

                    b.HasKey("CourseStudentRelationshipID");

                    b.ToTable("CourseStudentRelationship");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Exam", b =>
                {
                    b.Property<int>("Exam_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Exam_Distenation");

                    b.Property<string>("Exam_Image");

                    b.Property<string>("Exam_Script");

                    b.Property<string>("Exam_Title");

                    b.HasKey("Exam_ID");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Picture", b =>
                {
                    b.Property<int>("Picture_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Picture_Distenation");

                    b.Property<string>("Picture_Image");

                    b.Property<string>("Picture_Script");

                    b.Property<string>("Picture_Title");

                    b.HasKey("Picture_ID");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Professor", b =>
                {
                    b.Property<int>("Professor_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Professor_Email");

                    b.Property<string>("Professor_FullName");

                    b.Property<string>("Professor_Password");

                    b.HasKey("Professor_ID");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Project", b =>
                {
                    b.Property<int>("Project_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Project_Distenation");

                    b.Property<string>("Project_Image");

                    b.Property<string>("Project_Script");

                    b.Property<string>("Project_Title");

                    b.HasKey("Project_ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Reading", b =>
                {
                    b.Property<int>("Reading_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Readings_Content");

                    b.Property<string>("Readings_Image");

                    b.Property<string>("Readings_Reading_Title");

                    b.Property<string>("Readings_Script");

                    b.HasKey("Reading_ID");

                    b.ToTable("Reading");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Requests", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Request_CourseID");

                    b.Property<int>("Request_StudentID");

                    b.HasKey("RequestID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Sheet", b =>
                {
                    b.Property<int>("Sheet_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Sheet_Distenation");

                    b.Property<string>("Sheet_Image");

                    b.Property<string>("Sheet_Script");

                    b.Property<string>("Sheet_Title");

                    b.HasKey("Sheet_ID");

                    b.ToTable("Sheet");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Student", b =>
                {
                    b.Property<int>("Student_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Student_Email");

                    b.Property<string>("Student_FullName");

                    b.Property<string>("Student_PassWord");

                    b.HasKey("Student_ID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ExaminaFinalVersion.Models.Video", b =>
                {
                    b.Property<int>("Video_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Course_ID");

                    b.Property<string>("Video_Distenation");

                    b.Property<string>("Video_Image");

                    b.Property<string>("Video_Title");

                    b.Property<int>("Video_script");

                    b.HasKey("Video_ID");

                    b.ToTable("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
